//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;

    public partial class CauHinh
    {
        public int ID { get; set; }
        public string TenThuocTinh { get; set; }
        public string KieuDuLieu { get; set; }
        public string GiaTri { get; set; }
        public string DieuKien { get; set; }
    }
}