//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.ChiTietPhieuThues = new HashSet<ChiTietPhieuThue>();
        }
    
        public int SoPhong { get; set; }
        public Nullable<int> ID_LoaiPhong { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuThue> ChiTietPhieuThues { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }

        public string TenLoaiPhong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> SLKhachToiDa { get; set; }

        //For Binding
        public string ID_For_Binding { get; set; }
        public int STT_For_Binding { get; set; }
        public string Density_For_Binding { get; set; }
        public string Percent_For_Binding { get; set; }
    }
}
